# Generated by Django 6.0.5 on 2026-05-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
